// Primitive Data Types
// Primitive data types in JavaScript include:

// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor
// Non-primitive data types in JavaScript includes:

// Objects
// Arrays


let numOne = 3
let numTwo = 3

console.log(numOne == numTwo)      // true


let nums = [1, 2, 3]
let numbers = [1, 2, 3]

console.log(nums == numbers)  // false

let userOne = {
name:'ugur',
role:'studying',
country:'Turkey'
}

let userTwo = {
name:'ugur',
role:'studying',
country:'Turkey'
}

console.log(userOne == userTwo) // false


let nums1 = [1, 2, 3]
let numbers1 = nums1

console.log(nums == numbers)  // true

let userOne1 = {
name:'ugur',
role:'studying',
country:'Turkey'
}

let userTwo1 = userOne1

console.log(userOne1 == userTwo1)  // true


let age = 35
const gravity = 9.81  // we use const for non-changing values, gravitational constant in  m/s2
let mass = 72         // mass in Kilogram
const PI = 3.14       // pi a geometrical constant

PI = Math.PI

console.log(PI)                            // 3.141592653589793

console.log(Math.round(PI))                // 3 to round values to the nearest number

console.log(Math.round(9.81))              // 10

console.log(Math.floor(PI))                // 3 rounding down

console.log(Math.ceil(PI))                 // 4 rounding up

console.log(Math.min(-5, 3, 20, 4, 5, 10)) // -5, returns the minimum value

console.log(Math.max(-5, 3, 20, 4, 5, 10)) // 20, returns the maximum value

// Let us  create random number between 0 to 10

const num = Math.floor(Math.random () * 11) // creates random number between 0 and 10
console.log(num)

//Absolute value
console.log(Math.abs(-10))      // 10

//Square root
console.log(Math.sqrt(100))     // 10

console.log(Math.sqrt(2))       // 1.4142135623730951

// Power
console.log(Math.pow(3, 2))     // 9

console.log(Math.E)             // 2.718

// Trigonometry
Math.sin(0)
Math.sin(60)

Math.cos(0)
Math.cos(60)

// Returns the natural logarithm of 2 and 10 respectively
console.log(Math.LN2)           // 0.6931471805599453
console.log(Math.LN10)          // 2.302585092994046


//Random Number Generator
let randomNum = Math.random()         // generates 0 to 0.999
let numBtnZeroAndTen = randomNum * 11

console.log(numBtnZeroAndTen)         // this gives: min 0 and max 10.99

let randomNumRoundToFloor = Math.floor(numBtnZeroAndTen)
console.log(randomNumRoundToFloor)    // this gives between 0 and 10

//Strings

let space = ' '           // an empty space string
let firstName = 'Ugur'
let lastName = 'Kilic'
let country = 'Turkey'
let city = 'Ankara'
let language = 'JavaScript'
let fullName = firstName + space + lastName; // concatenation, merging two string together.

//Long Literal Strings

const paragraph = "My name is Asabeneh Yetayeh. I live in Finland, Helsinki.\
I am a teacher and I love teaching. I teach HTML, CSS, JavaScript, React, Redux, \
Node.js, Python, Data Analysis and D3.js for anyone who is interested to learn. \
In the end of 2019, I was thinking to expand my teaching and to reach \
to global audience and I started a Python challenge from November 20 - December 19.\
It was one of the most rewarding and inspiring experience.\
Now, we are in 2020. I am enjoying preparing the 30DaysOfJavaScript challenge and \
I hope you are enjoying too."

console.log(paragraph)

//Escape Sequences in Strings

/*
\n: new line
\t: Tab, means 8 spaces
\\: Back slash
\': Single quote (')
\": Double quote (")


I hope everyone is enjoying the 30 Days Of JavaScript challenge.
Do you ?
Days  Topics  Exercises
Day 1 3 5
Day 2 3 5
Day 3 3 5
Day 4 3 5
This is a backslash  symbol (\)
In every programming language it starts with "Hello, World!"
In every programming language it starts with 'Hello, World!'
The saying 'Seeing is Believing' isn't correct in 2020
*/

// Template Literals (Template Strings)

//Syntax
`String literal text`
`String literal text ${expression}`

// String Methods

let js = 'JavaScript'
console.log(js.length)         // 10

let string = 'JavaScript'

console.log(string.substring(0,4))     // Java
console.log(string.substring(4,10))    // Script
console.log(string.substring(4))       // Script

let string1 = '30 Days Of JavaScript'

console.log(string1.split())     // Changes to an array -> ["30 Days Of JavaScript"]
console.log(string1.split(' '))  // Split to an array at space -> ["30", "Days", "Of", "JavaScript"]
console.log(string1.includes('Days'))     // true
console.log(string1.includes('days'))     // false - it is case sensitive!
console.log(string1.replace('JavaScript', 'Python')) // 30 Days Of Python

let string2 = '30 Days Of JavaScript'
console.log(string2.charCodeAt(3))        // D ASCII number is 68

let lastIndex = string2.length - 1
console.log(string2.charCodeAt(lastIndex)) // t ASCII is 116

let string4 = 'I love JavaScript. If you do not love JavaScript what else can you love.'
let pattern = /love/gi
console.log(string4.match(pattern))   // ["love", "love", "love"]